name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.18'
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}
      - run: go version
      - run: go generate
      - run: go run test/data/gen.go
      - run: go test -v
