name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Gen RSA
        run: |
          mkdir -p test/data/rsa
          for i in {0..6}; do
            scripts/genrsa.sh test/data/rsa/"$i"_priv.pem test/data/rsa/"$i"_pub.pem
          done
      - run: go test -v
        working-directory: test
